SOT-131: Add Folding Scheme for Committed Relaxed R1CS
sota-zk-labs/zkp-documents pull request #61
Opened 2024-05-19 15:45 UTC by VanhGer

# Check List

- [ ] Did you check your grammar / reader proof your document using ChatGPT?
- [ ] Don't forget to squash commits into meaningful chunks before merging
- [ ] After merging this, please update your task status!
- [ ] Did you verify that your math formulas are rendered correctly?

2024-05-19 16:52 UTC, zk-steve commented on docs/nova.md
fix broken image in this https://github.com/sota-zk-labs/zkp-documents/blob/sot-131/terms/r1cs.md by adding a new line below the image's link

2024-05-19 18:26 UTC, zk-steve commented on docs/nova.md
> +For Committed Relaxed R1CS, we uses succinct and hiding additively
```suggestion
For Committed Relaxed R1CS, we use succinct and hiding additively 
```

2024-05-19 19:32 UTC, zk-steve commented on docs/nova.md
> +We can make this protocol non-interactive via [Fiat-Shamir](../terms/fiat_shamir.md). Let $\rho$ denote a random oracle, then the
link the random oracle

2024-05-19 19:32 UTC, zk-steve requested changes
Few things left then it's good to go!

2024-05-20 03:31 UTC, zk-steve approved these changes

2024-05-20 04:25 UTC, ktokto313 approved these changes
chat a

2024-05-20 07:27 UTC, merged